import packager from "electron-packager";

(async (): Promise<void> => {
  await packager({
    dir: process.cwd(),
    overwrite: true,
    ignore: [
      /(node_modules)/,
      /(\.eslintrc\.json)/,
      /(\.github)/,
      /(\.\\source)/,
      /(package-lock\.json)/,
      /(\.gitignore)/,
      /(README\.md)/,
      /(package-lock\.json)/,
      /(webpack\.config\.ts)/,
      /(release-builds)/,
      /(tsconfig\.json)/,
      /(audit-ci\.json)/,
      /(\.prettierrc\.json)/, // to zostaw
      /(\.\\android)/,
      /(\.\\bundle-analyzes)/,
      /(\.\\dockerfiles)/,
      /(\.\\ios)/,
      /(\.\\gun-database)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(\.prettierrc\.json)/,
      /(tsconfig\.node\.json)/,
      /(tsconfig\.tsbuildinfo)/,
      /(tslint\.json)/,
      /(vite\.config\.ts)/,
      /(yarn-error\.log)/,
      /(\.\\storyboo)/,
      /(\.\\husky)/,
    ],
    platform: "win32",
    arch: "x64",
    prune: true,
    out: "release-builds",
    asar: true,
    prebuiltAsar: false,
  });
})();
