name: "auto-merge-dependabot"
on:
  pull_request:
jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: self-hosted
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - run: npm install -g yarn
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - uses: actions/checkout@v3
      - run: yarn --ignore-engines
        with:
          repository: "https://github.com/ZSBRybnik/backend"
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential libpcap-dev -y
      - run: yarn --ignore-engines
      - run: yarn run build-web
      - run: yarn run test
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.token }}
