name: "auto-merge-dependabot"
on:
  pull_request:
jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ZSBRybnik/backend
          path: ./backend
      - uses: actions/checkout@v3
        with:
          path: ./frontend
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: |
            ./backend/yarn.lock
            ./frontend/yarn.lock
      - run: npm install -g yarn ts-node
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "./frontend/source/native-addon-python/requirements.txt"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - run: yarn --ignore-engines
        working-directory: ./backend
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential libpcap-dev -y
      - run: yarn --ignore-engines
        working-directory: ./frontend
      - run: yarn run test
        working-directory: ./frontend
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.token }}
